### ISSUE TITLE
Work with Angular 1.4?

### ISSUE THREAD

**Issue by mattiLeBlanc** [dotansimha/angular-reactive-component#3]
Hi,

I see the dependency of Angular2-now. However, what If I use it with `pbastowski:typescript` only?
I do get some errors on ` this.$scope.stopOnDestroy is not a function` so maybe it won't work with Angular1.4 + Meteor and Typescript.
Or is it fairly easy to make this work?

**Comment by mattiLeBlanc** [comment]
okay, actually it does work with Angular1.4, as long as I do inject $scope and $reactive :).

I think it is still worth extending my controller with ReactiveComponent because now I can just call this.subscribe without have to create a reactiveContext.

So my code is: 

```
class DashboardController extends ReactiveComponent {

  static $inject = [ '$log', '$state', 'authService', '$modal', '$scope' , '$reactive'];

  public  myModal: any;
  
  private invoiceFilter = {
    'AmountDue': { $gt: 0 }
  };
 constructor( private $log: angular.ILogService, private $state: angular.ui.IStateService, private authService: any, private $modal: any, private $scope: any, $reactive: any ) {
    super( arguments );
    this.subscribe( 'invoices', () => [ this.invoiceFilter 
    ] );
    
    this.helpers( {
      invoices: () => Invoices.find( {} )
    } );
  }
}
this.DashboardController = DashboardController;
```

Cheers.

**Comment by ozsay** [comment]
Is there any issue here or you found a fix ?

**Comment by mattiLeBlanc** [comment]
It was more a discovery cause I thought ReactiveComponent was only for Angular2now. However it does work with pbastowski:typescrip.
